IMAGE_NAME = "generic/ubuntu1804"
N = 3

Vagrant.configure("2") do |config|
    config.ssh.insert_key = 'false'
    config.vm.provider :libvirt do |libvirt|
        libvirt.memory = 8192
        libvirt.cpus = 4
        libvirt.storage :file, :size => '50G'
        libvirt.graphics_type = 'vnc'
        libvirt.graphics_port = '5901'
        libvirt.graphics_ip = '0.0.0.0'
    end
      
    config.vm.define "master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "public_network", bridge: "br0", dev: "br0", type: "bridge", mode: "bridge", ip: "192.168.1.175"
        master.vm.hostname = "master"
        master.vm.provision "ansible" do |ansible|
                ansible.playbook = "master.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.1.175",
                }
        end
    end
end


Vagrant.configure("2") do |config|
    config.ssh.insert_key = 'false'
    config.vm.provider :libvirt do |v|
        v.memory = 4096
        v.cpus = 2
        v.storage :file, :size => '50G'
    end

    (1..N).each do |i|
        config.vm.define "ubu-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "public_network", bridge: "br0", dev: "br0", type: "bridge", mode: "bridge", ip: "192.168.1.#{i + 175}"
            node.vm.hostname = "ubu-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "node.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.1.#{i + 175}",
                }
            end
        end
    end
end

