# shell provision halp:
# https://automation-remarks.com/setting-vagrant/

IMAGE_NAME = "generic/ubuntu2004"
#N = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = 'false'
    config.vm.provider :virtualbox do |virtualbox|
        virtualbox.memory = 4096
        virtualbox.cpus = 2
    end
      
    config.vm.define "ubuforwin" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "public_network", mode: "bridge", ip: "192.168.1.180"
        #master.ssh.private_key_path = "~/.ssh/id_rsa"
        master.ssh.forward_agent = true
        master.vm.hostname = "ubuforwin"
        master.vm.provision "shell", inline: <<-SHELL
            set -e
            sudo ip route del default via 10.0.2.2
            sudo ip route add default via 192.168.1.1
            sudo git config --global user.name "morozovme"
            sudo git config --global user.email "m.e.morozov1@gmail.com"
            sudo apt-get update -y
            git clone --branch ubuntu20 https://github.com/morozovme/infra.git
            sudo mkdir -p /etc/docker
            sudo touch /etc/docker/daemon.json
            sudo tee -a /etc/docker/daemon.json <<EOF
{
"registry-mirrors": ["http://192.168.1.88:6000"]
}
EOF
            curl http://192.168.1.88:6000/v2/_catalog
            sudo chmod +x infra/install/dockerinst.sh && sudo ./infra/install/dockerinst.sh
            sudo chmod +x infra/install/docomposeinst.sh && sudo ./infra/install/docomposeinst.sh
            #sudo apt-get update
            #cd infrastructure_scripts/ubuntu18/ && sudo chmod +x dockerinst.sh && sudo ./dockerinst.sh
            #cd ../../
            git clone https://github.com/morozovme/main_app.git
            cd main_app
            sudo docker build -t morozovme/main-app .
            sudo docker run -d -p 8084:8084 morozovme/main-app
            cd ..
            git clone https://github.com/morozovme/rvproxy.git
            cd rvproxy
            sudo docker build -t morozovme/rvproxy .
            sudo docker run -d -p 80:80 morozovme/rvproxy
            cd ..
            #git clone --branch compozation https://github.com/morozovme/koa_app.git
            git clone https://github.com/morozovme/koa_app.git
            cd koa_app && sudo docker-compose up --detach
            cd ../
            git clone --branch feature/lists https://github.com/morozovme/koa_app.git koa_app_lists
            cd koa_app_lists && sudo docker-compose up --detach
            sudo apt-get install npm -y
            cd backend && sudo npm install && sudo ./databasemigration.sh
            
            #git clone https://github.com/morozovme/nodejs_streaming_app.git
            cd /home/vagrant
            git clone https://github.com/morozovme/nodejs_blogapp.git
            cd nodejs_blogapp && sudo docker-compose up --detach
            cd ..
            git clone https://github.com/morozovme/flaskr-tdd.git
            cd flaskr-tdd && sudo docker build -t morozovme/flaskr . && sudo docker run -d -p 8087:8087 -t morozovme/flaskr
            #sudo docker run -d -p 6000:5000 -e REGISTRY_PROXY_REMOTEURL=http://192.168.1.88:6000 --restart always --name registry registry:2
            #sudo rm -f /etc/docker/daemon.json
            #echo "{\"registry-mirrors\": [\"http://127.0.0.1:6000\"]}" | sudo tee /etc/docker/daemon.json
            
        SHELL



# chef provisioning example
    #    config.vm.provision :chef_solo do |chef|
    #      chef.arguments = "--chef-license accept"
    #      chef.cookbooks_path = "cookbooks"
    #      chef.roles_path = "cookbooks/roles"
    #      chef.add_role("vagrant")
    #    end
    end
end

#Vagrant.configure("2") do |config|
#    config.ssh.insert_key = 'false'
#    config.vm.provider :virtualbox do |v|
#        v.memory = 2048
#        v.cpus = 2
#    end
#
#    (1..N).each do |i|
#        config.vm.define "node-#{i}" do |node|
#            node.vm.box = IMAGE_NAME
#            node.vm.network "public_network", mode: "bridge", ip: "192.168.1.#{i + 170}"
#            node.vm.hostname = "node-#{i}"
#        end
#    end
#end
