# shell provision halp:
# https://automation-remarks.com/setting-vagrant/

IMAGE_NAME = "bento/ubuntu2004"
#N = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = 'false'
    config.vm.provider :virtualbox do |virtualbox|
        virtualbox.memory = 4096
        virtualbox.cpus = 2
    end
      
    config.vm.define "ubuforwin" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "public_network", mode: "bridge", ip: "192.168.1.88"
        #master.ssh.private_key_path = "~/.ssh/id_rsa"
        master.ssh.forward_agent = true
        master.vm.hostname = "ubuforwin"
        master.vm.provision "shell", inline: <<-SHELL
            sudo ip route del default via 10.0.2.2
            sudo ip route add default via 192.168.1.1
            sudo git config --global user.name "mikefrostov"
            sudo git config --global user.email "m.e.morozov1@gmail.com"
            sudo apt-get update -y
            git clone --branch ubuntu20 https://github.com/mikefrostov/infra.git
            sudo chmod +x infra/install/dockerinst.sh && sudo ./infra/install/dockerinst.sh
            sudo chmod +x infra/install/docomposeinst.sh && sudo ./infra/install/docomposeinst.sh
            #sudo apt-get update
            #cd infrastructure_scripts/ubuntu18/ && sudo chmod +x dockerinst.sh && sudo ./dockerinst.sh
            #cd ../../
            git clone https://github.com/mikefrostov/main_app.git
            cd main_app
            sudo docker build -t mikefrostov/main-app .
            sudo docker run -d -p 8084:8084 mikefrostov/main-app
            cd ..
            git clone https://github.com/mikefrostov/rvproxy.git
            cd rvproxy
            sudo docker build -t mikefrostov/rvproxy .
            sudo docker run -d -p 80:80 mikefrostov/rvproxy
            cd ..
            git clone --branch compozation https://github.com/mikefrostov/koa_app.git
            
        SHELL

# chef provisioning example
    #    config.vm.provision :chef_solo do |chef|
    #      chef.arguments = "--chef-license accept"
    #      chef.cookbooks_path = "cookbooks"
    #      chef.roles_path = "cookbooks/roles"
    #      chef.add_role("vagrant")
    #    end
    end
end

#Vagrant.configure("2") do |config|
#    config.ssh.insert_key = 'false'
#    config.vm.provider :virtualbox do |v|
#        v.memory = 2048
#        v.cpus = 2
#    end
#
#    (1..N).each do |i|
#        config.vm.define "node-#{i}" do |node|
#            node.vm.box = IMAGE_NAME
#            node.vm.network "public_network", mode: "bridge", ip: "192.168.1.#{i + 170}"
#            node.vm.hostname = "node-#{i}"
#        end
#    end
#end
