---

- hosts: all
  become: true
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: change default route
    command: route add default gw 192.168.1.1 eth1

  - name: delete vagrant default route
    command: route del default gw 192.168.121.1 eth0

  - name: add default gw to /etc/network/interfaces
    lineinfile:
      path: /etc/network/interfaces
      line: '      gateway 192.168.1.1'

  - name: add l2j to /etc/hosts
    lineinfile:
      path: /etc/hosts
      line: 192.168.1.180 l2j l2j

#  - name: Add an apt signing key for Docker
#    apt_key:
#      url: https://download.docker.com/linux/ubuntu/gpg
#      state: present
#
#  - name: Add apt repository for stable version
#    apt_repository:
#      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
#      state: present

#  - name: Install docker and its dependecies
#    apt:
#      name: "{{ packages }}"
#      state: present
#      update_cache: yes
#    vars:
#      packages:
#      - docker-ce
#      - docker-ce-cli
#      - containerd.io
#    notify:
#      - docker status

#  - name: Add vagrant user to docker group
#    user:
#      name: vagrant
#      group: docker

  - name: clone of a single branch
    ansible.builtin.git:
      repo: https://github.com/TheDemonLife/Lineage2-Server-Interlude.git
      dest: /home/vagrant/Lineage2-Server-Interlude
      version: master

#  - name: download navicat repository
#    become: false
#    command: wget -q -O - http://www.navicat.com/download_linux_repo?lnx_repo=ubuntu | sudo tee /etc/apt/sources.list.d/navicatmonitor.list

#  - name: install repo
#    become: false
#    command: tee /etc/apt/sources.list.d/navicatmonitor.list
#
#  - name: install navicat
#    become: false
#    command: sudo apt-get update && sudo apt-get install navicatmonitor
#
#  - name: run navicat
#    become: false
#    command: sudo /etc/init.d/navicatmonitor start

  - name: Ensure Java is installed.
    apt:
      name: openjdk-8-jre-headless
      state: present

  - name: Download get-pip.py 
    get_url:
      url: 'https://bootstrap.pypa.io/pip/3.5/get-pip.py'
      dest: /tmp/get-pip.py

  - name: Install pip
    command: "python3 /tmp/get-pip.py"

  - name: Make sure pymysql is present
    become: true # needed if the other tasks are not played as root
    pip:
      name: pymysql
      state: present

  - name: Install MySQL
    apt:
      state: present
      name: 
      - mysql-server
      - mysql-client
      - libmysqlclient-dev
      - python-mysqldb

#  - name: mysql secure installation
#    expect: 
#      command: "mysql_secure_installation"
#      responses:
#        'First Question in the prompt' : 'y'
#    become: true

  - name: Start the MySQL service
    action: service name=mysql state=started

#  - name: Update mysql root password for all root accounts
#    mysql_user: name=root host={{item}} password=""
#    with_items:
#      - 127.0.0.1
#      - ::1
#      - localhost

  - name: Set MySQL root Password
    mysql_user:
      #login_host: 'localhost'
      login_unix_socket: /var/run/mysqld/mysqld.sock
      login_user: 'root'
      login_password: ''
      name: 'root'
      password: '1q2w3e'
      priv: '*.*:ALL,GRANT'
      state: present

  - name: Create a new database with name 'la2_login'
    community.mysql.mysql_db:
      name: la2_login
      login_user: root
      login_password: '1q2w3e'
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: present

  - name: Create a new database with name 'la2_game'
    community.mysql.mysql_db:
      name: la2_game
      login_user: root
      login_password: '1q2w3e'
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: present

#  - name: Changing perm of "/foo/bar.sh", adding "+x"
#    file: dest=/home/vagrant/Lineage2-Server-Interlude/login/*.sh mode=a+x
#    become: true

  - name: Changing perm adding +x
    file: 
      path: "{{ item }}"
      mode: a+x
    with_items:
      - /home/vagrant/Lineage2-Server-Interlude/login/start.sh
      - /home/vagrant/Lineage2-Server-Interlude/login/loop.sh
      - /home/vagrant/Lineage2-Server-Interlude/login/account_manager.sh
      - /home/vagrant/Lineage2-Server-Interlude/login/register_gameserver.sh
    become: true

  - name: add mysql password to config
    lineinfile:
      path: /home/vagrant/Lineage2-Server-Interlude/login/config/main/network.properties
      regexp: '^(.*)Password =(.*)$'
      line: Password = 1q2w3e
    become: true
# grant privelges to root!!! 
# example
# GRANT ALL PRIVILEGES ON la2_login.* TO 'root'@'localhost';


#  - name: Copy .my.cnf file with root password credentials
#    template: .my.cnf dest=/etc/mysql/my.cnf owner=root mode=0600

#  - name: update mysql root password for all root accounts
#    mysql_user: 
#      name: root 
#      host: "l2j" 
#      password: ""
#      login_user: root
#      login_password: ""
#      check_implicit_admin: yes
#      priv: "*.*:ALL,GRANT"
#    with_items:
#      - "l2j"
#      - 127.0.0.1
#      - ::1
#      - localhost 


#  - name: Remove the test database
#    mysql_db: name=test state=absent

#  - name: Create deploy user for mysql
#    mysql_user: user="deploy" host="%" password="1q2w3e" priv=*.*:ALL,GRANT

#  - name: Ensure anonymous users are not in the database
#    mysql_user: user='' host=$item state=absent
#    with_items:
#      - 127.0.0.1
#      - ::1
#      - localhost

# change line with root password in login server config for mysql 


#  - name: add +x to *.sh
#    command: chmod +x Lineage2/login/*.sh
#    become: yes 

#  - name: run login server
#    command: ./Lineage2/login/start.sh
#    become: yes


  handlers:
  - name: docker status
    service: name=docker state=started


# add install mysql 
# add install java 

# add install other stuff
# add install l2j 
# configure l2j for it to work




