IMAGE_NAME = "generic/ubuntu1604"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = 'false'
    config.vm.provider :libvirt do |libvirt|
        libvirt.memory = 4096
        libvirt.cpus = 2
        libvirt.storage :file, :size => '50G'
    end
      
    config.vm.define "l2j" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "public_network", bridge: "br0", dev: "br0", type: "bridge", mode: "bridge", ip: "192.168.1.180"
        master.vm.hostname = "l2j"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "l2j/playbook.yml"
            ansible.extra_vars = {
                node_ip: "192.168.1.180",
            }
        end
    end
end
